import { MarkerData, CategoryInfo } from './types';

export const CATEGORIES: Record<string, CategoryInfo> = {
  city: { label: 'City / Town', color: '#3b82f6', icon: '🏙️' },
  beach: { label: 'Beach / Coast', color: '#14b8a6', icon: '🏖️' },
  landmark: { label: 'Landmark', color: '#ef4444', icon: '🏛️' },
  nature: { label: 'Nature', color: '#22c55e', icon: '🌿' },
  food: { label: 'Food / Local', color: '#f97316', icon: '🍜' },
  custom: { label: 'Custom', color: '#a855f7', icon: '📍' },
};

export const COLOR_MAP: Record<string, string> = {
  '#3b82f6': 'blue',
  '#ef4444': 'red',
  '#22c55e': 'green',
  '#f97316': 'orange',
  '#a855f7': 'purple',
  '#14b8a6': 'teal',
};

export const initialMarkers: MarkerData[] = [
  {
    id: '1',
    name: 'Dagupan City',
    description: 'The capital of Pangasinan, famous for Bangus (milkfish) and festivals.',
    lat: 16.0425,
    lng: 120.3486,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '2',
    name: 'Lingayen',
    description: 'Provincial capital known for its beautiful beach and the Lingayen Gulf.',
    lat: 16.0228,
    lng: 120.2369,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '3',
    name: 'Hundred Islands National Park',
    description: 'A group of 124 islands, famous for white sand beaches and crystal clear waters.',
    lat: 16.0917,
    lng: 119.9817,
    category: 'beach',
    color: '#14b8a6',
  },
  {
    id: '4',
    name: 'Alaminos',
    description: 'Gateway city to the Hundred Islands National Park.',
    lat: 16.1078,
    lng: 120.0344,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '5',
    name: 'San Carlos City',
    description: 'A component city in the northern part of Pangasinan.',
    lat: 16.1078,
    lng: 120.3703,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '6',
    name: 'Urdaneta City',
    description: 'Known as the "Mabuhay City" - a major commercial center in eastern Pangasinan.',
    lat: 15.9767,
    lng: 120.5689,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '7',
    name: 'Bolinao Beach',
    description: 'A stunning beach destination in the western part of Pangasinan with white sand.',
    lat: 16.0017,
    lng: 119.9389,
    category: 'beach',
    color: '#14b8a6',
  },
  {
    id: '8',
    name: 'Pozorrubio',
    description: 'A municipality known for its agricultural products and local culture.',
    lat: 16.1356,
    lng: 120.5567,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '9',
    name: 'Manaoag Church',
    description: 'A famous pilgrimage site housing the Our Lady of the Most Holy Rosary.',
    lat: 16.1603,
    lng: 120.6156,
    category: 'landmark',
    color: '#ef4444',
  },
  {
    id: '10',
    name: 'Cape Bolinao Lighthouse',
    description: 'Historic lighthouse built in 1892, offering panoramic views of the South China Sea.',
    lat: 16.0056,
    lng: 119.9422,
    category: 'landmark',
    color: '#ef4444',
  },
  {
    id: '11',
    name: 'Tambobong White Beach',
    description: 'A pristine white sand beach in Dasol, Pangasinan.',
    lat: 16.0500,
    lng: 119.8800,
    category: 'beach',
    color: '#14b8a6',
  },
  {
    id: '12',
    name: 'Binalonan',
    description: 'Known for the Bago Festival and its agricultural heritage.',
    lat: 16.0019,
    lng: 120.5536,
    category: 'city',
    color: '#3b82f6',
  },
  {
    id: '13',
    name: 'Pangasinan Bangus (Milkfish)',
    description: 'Pangasinan is the milkfish capital of the Philippines. Try the boneless bangus!',
    lat: 16.0425,
    lng: 120.3550,
    category: 'food',
    color: '#f97316',
  },
  {
    id: '14',
    name: 'Pindang (Local Delicacy)',
    description: 'A traditional Pangasinan delicacy of salted and dried meat, especially carabao.',
    lat: 16.0228,
    lng: 120.2450,
    category: 'food',
    color: '#f97316',
  },
  {
    id: '15',
    name: 'Mt. Cabuyao',
    description: 'A dormant volcano offering hiking trails and scenic views of Pangasinan.',
    lat: 16.0500,
    lng: 120.1500,
    category: 'nature',
    color: '#22c55e',
  },
];
